apiVersion: v1
kind: Service
metadata:
  name: formatura-service
  namespace: formatura
spec:
  selector:
    app: formatura
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
